trigger:
- main

pool:
  name: 'webgoat-agent'

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: CopyFiles@2
    inputs:
      contents: '**/target/*.jar'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'webgoat_artifact'
      publishLocation: 'Container'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'webgoat_artifact'
      path: '$(Pipeline.Workspace)/webgoat_artifact'

  - script: |
      ls $(Pipeline.Workspace)/webgoat_artifact
    displayName: 'List downloaded artifact contents'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Free Trial(02dd8a70-8b78-44e2-bb9e-56d6e1188f39)'
      appType: 'webAppLinux'
      WebAppName: 'webgaottest'
      packageForLinux: '$(Pipeline.Workspace)/webgoat_artifact/**/*.jar'
      RuntimeStack: 'TOMCAT|10.0-java21'
